name=TPS92520-Arduino
version=0.1.0
author=Matthew Barr
maintainer=Matthew Barr
sentence=Arduino driver for the TI TPS92520-Q1 LED driver.
paragraph=Provides current control, telemetry, status monitoring and SPI protocol abstraction.
category=Device Control
url=https://github.com/DrMattGBarr/TPS92520-Arduino
architectures=*